AllCops:
  Exclude:
    - 'spec/**/*'

Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/SpecialGlobalVars:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false
